---
title: "'Catch' non può trovarsi all'esterno di un'istruzione 'Try'"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: f9ce965d1d983743796f8cc66ae20ffb018a07bc
ms.sourcegitcommit: 0be8a279af6d8a43e03141e349d3efd5d35f8767
ms.translationtype: HT
ms.contentlocale: it-IT
ms.lasthandoff: 04/18/2019
ms.locfileid: "59295913"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' non può trovarsi all'esterno di un'istruzione 'Try'
`Catch` deve figurare all'interno di un blocco di istruzioni `Try...Catch...Finally` . Nel blocco `Catch` è presente un'istruzione `Try` non necessaria oppure l'istruzione `Catch` si trova al di fuori dei limiti del blocco `Try` corrispondente.  
  
 **ID errore:** BC30380  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
1. Eliminare l'istruzione `Catch` se non è necessaria oppure inserirla all'interno di un blocco di istruzioni `Try...Catch...Finally` .  
  
## <a name="see-also"></a>Vedere anche

- [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
