---
title: L'istruzione 'Throw' non può omettere l'operando all'esterno di un'istruzione 'Catch' o all'interno di un'istruzione 'Finally'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 17185ec328cecc29560b28e878682005e2a8a9e8
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 12/22/2018
ms.locfileid: "53768116"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>L'istruzione 'Throw' non può omettere l'operando all'esterno di un'istruzione 'Catch' o all'interno di un'istruzione 'Finally'
Le istruzioni`Throw` di fuori dell'istruzione `Catch` devono fornire il nome di un oggetto eccezione.  
  
 **ID errore:** BC30666  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
1.  Specificare il nome di un oggetto eccezione derivato da `System.Exception`.  
  
2.  Ristrutturare il codice in modo che l'istruzione `Throw` si trovi in un blocco `Catch` .  
  
## <a name="see-also"></a>Vedere anche  
 [Istruzione Throw](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Classe di eccezione in Visual Basic](https://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [Gestione di eccezioni ed errori in Visual Basic](https://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
