---
title: Blocco 'Catch' mai raggiunto perché '<name1>'eredita da'<name2>'
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: fe716108281b3df64c3d444c54bee8dea3fcb82f
ms.sourcegitcommit: 2701302a99cafbe0d86d53d540eb0fa7e9b46b36
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 04/28/2019
ms.locfileid: "64755850"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>Blocco 'Catch' mai raggiunto perché '\<name1 >' eredita da '\<nome2 >'
Un blocco `Catch` all'interno del codice non viene mai raggiunto.  
  
 Per impostazione predefinita, si tratta di un messaggio di avviso. Per altre informazioni su come nascondere gli avvisi o considerarli come errori, vedere [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **ID errore:** BC42029  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
- Rimuovere il blocco `Catch` estraneo.  
  
## <a name="see-also"></a>Vedere anche

- [Come usare il blocco try/catch per intercettare le eccezioni](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
