---
title: Blocco 'Catch' mai raggiunto. &lt;eccezione&gt; viene gestito sopra nella stessa istruzione 'Try'
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: f783da40cf1be7132975e9f8b8d740b7f791a796
ms.sourcegitcommit: 6b308cf6d627d78ee36dbbae8972a310ac7fd6c8
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 01/23/2019
ms.locfileid: "54715673"
---
# <a name="catch-block-never-reached-ltexceptiongt-handled-above-in-the-same-try-statement"></a>Blocco 'Catch' mai raggiunto. &lt;eccezione&gt; viene gestito sopra nella stessa istruzione 'Try'
Un blocco `Catch` nel codice non è raggiungibile perché è gestito in un blocco `Try` precedente.  
  
 Per impostazione predefinita, si tratta di un messaggio di avviso. Per altre informazioni su come nascondere gli avvisi o considerarli come errori, vedere [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **ID errore:** BC42031  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
-   Rimuovere l'istruzione ridondante.  
  
## <a name="see-also"></a>Vedere anche
- [Procedura: Rilevare un'eccezione in Visual Basic](https://msdn.microsoft.com/library/f3063c89-d2bf-49b1-91b5-b87edfb18b95)
- [Procedura: Testare il codice con un blocco Try... Blocco catch in Visual Basic](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)
- [Procedura: Filtrare gli errori in un blocco Catch in Visual Basic](https://msdn.microsoft.com/library/85964d0a-56e7-4301-a96e-5eaea23b7b9b)
- [Procedura dettagliata: (Visual Basic) di gestione strutturata delle eccezioni](https://msdn.microsoft.com/library/440da655-4b32-490b-8b16-bfe46f41fa76)
- [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
