---
title: Blocco 'Catch' mai raggiunto perché '<name1>'eredita da'<name2>'
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 89b916513633515ce5433d06e4cdda7039c688c3
ms.sourcegitcommit: 14355b4b2fe5bcf874cac96d0a9e6376b567e4c7
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 01/30/2019
ms.locfileid: "55289614"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>Blocco 'Catch' mai raggiunto perché '\<name1 >' eredita da '\<nome2 >'
Un blocco `Catch` all'interno del codice non viene mai raggiunto.  
  
 Per impostazione predefinita, si tratta di un messaggio di avviso. Per altre informazioni su come nascondere gli avvisi o considerarli come errori, vedere [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **ID errore:** BC42029  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
-   Rimuovere il blocco `Catch` estraneo.  
  
## <a name="see-also"></a>Vedere anche
- [Procedura: Testare il codice con un blocco Try... Blocco catch in Visual Basic](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)
- [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
