---
ms.openlocfilehash: 94fad6fe910da6c528c5e13f529a6db274e07d5c
ms.sourcegitcommit: 5b6d778ebb269ee6684fb57ad69a8c28b06235b9
ms.translationtype: HT
ms.contentlocale: it-IT
ms.lasthandoff: 04/08/2019
ms.locfileid: "59235695"
---
### <a name="change-in-behavior-for-taskwaitall-methods-with-time-out-arguments"></a><span data-ttu-id="449b9-101">Modifica del comportamento per i metodi Task.WaitAll con argomenti di timeout</span><span class="sxs-lookup"><span data-stu-id="449b9-101">Change in behavior for Task.WaitAll methods with time-out arguments</span></span>

|   |   |
|---|---|
|<span data-ttu-id="449b9-102">Dettagli</span><span class="sxs-lookup"><span data-stu-id="449b9-102">Details</span></span>|<xref:System.Threading.Tasks.Task.WaitAll%2A?displayProperty=nameWithType> <span data-ttu-id="449b9-103">In .NET Framework 4.5 il comportamento di Task.WaitAll è stato reso più coerente. In .NET Framework 4 questi metodi avevano un comportamento non coerente.</span><span class="sxs-lookup"><span data-stu-id="449b9-103">behavior was made more consistent in .NET Framework 4.5.In the .NET Framework 4, these methods behaved inconsistently.</span></span> <span data-ttu-id="449b9-104">Alla scadenza del timeout, se una o più attività sono state completate o annullate prima della chiamata al metodo, il metodo genera un'eccezione <xref:System.AggregateException?displayProperty=name>.</span><span class="sxs-lookup"><span data-stu-id="449b9-104">When the time-out expired, if one or more tasks were completed or canceled before the method call, the method threw an <xref:System.AggregateException?displayProperty=name> exception.</span></span> <span data-ttu-id="449b9-105">Alla scadenza del timeout, se nessuna attività è stata completata o annullata prima della chiamata al metodo, ma una o più attività sono entrate in questi stati dopo la chiamata al metodo, il metodo restituisce false.</span><span class="sxs-lookup"><span data-stu-id="449b9-105">When the time-out expired, if no tasks were completed or canceled before the method call, but one or more tasks entered these states after the method call, the method returned false.</span></span><br/><br/><span data-ttu-id="449b9-106">In .NET Framework 4.5 questi overload del metodo ora restituiscono false in presenza di attività ancora in esecuzione allo scadere dell'intervallo di timeout e generano un'eccezione <xref:System.AggregateException?displayProperty=name> solo se un'attività di input è stata annullata, indipendentemente dal fatto che sia stata annullata prima o dopo la chiamata del metodo, e non ci sono altre attività ancora in esecuzione.</span><span class="sxs-lookup"><span data-stu-id="449b9-106">In the .NET Framework 4.5, these method overloads now return false if any tasks are still running when the time-out interval expired, and they throw an <xref:System.AggregateException?displayProperty=name> exception only if an input task was cancelled (regardless of whether it was before or after the method call) and no other tasks are still running.</span></span>|
|<span data-ttu-id="449b9-107">Suggerimento</span><span class="sxs-lookup"><span data-stu-id="449b9-107">Suggestion</span></span>|<span data-ttu-id="449b9-108">Se veniva rilevata un'eccezione <xref:System.AggregateException?displayProperty=name> come mezzo per rilevare un'attività annullata prima della chiamata al metodo <xref:System.Threading.Tasks.Task.WaitAll%2A>, il codice doveva invece eseguire lo stesso rilevamento tramite la proprietà <xref:System.Threading.Tasks.Task.IsCanceled%2A> (ad esempio: .Any(t = &gt; t.IsCanceled)), in quanto in questo caso .NET Framework 4.6 genera un'eccezione solo se tutte le attività attese vengono completate prima del timeout.</span><span class="sxs-lookup"><span data-stu-id="449b9-108">If an <xref:System.AggregateException?displayProperty=name> was being caught as a means of detecting a task that was cancelled prior to the <xref:System.Threading.Tasks.Task.WaitAll%2A> call being invoked, that code should instead do the same detection via the  <xref:System.Threading.Tasks.Task.IsCanceled%2A> property (for example: .Any(t =&gt; t.IsCanceled)) since .NET Framework 4.6 will only throw in that case if all awaited tasks are completed prior to the timeout.</span></span>|
|<span data-ttu-id="449b9-109">Ambito</span><span class="sxs-lookup"><span data-stu-id="449b9-109">Scope</span></span>|<span data-ttu-id="449b9-110">Secondario</span><span class="sxs-lookup"><span data-stu-id="449b9-110">Minor</span></span>|
|<span data-ttu-id="449b9-111">Versione</span><span class="sxs-lookup"><span data-stu-id="449b9-111">Version</span></span>|<span data-ttu-id="449b9-112">4.5</span><span class="sxs-lookup"><span data-stu-id="449b9-112">4.5</span></span>|
|<span data-ttu-id="449b9-113">Tipo</span><span class="sxs-lookup"><span data-stu-id="449b9-113">Type</span></span>|<span data-ttu-id="449b9-114">Runtime</span><span class="sxs-lookup"><span data-stu-id="449b9-114">Runtime</span></span>|
|<span data-ttu-id="449b9-115">API interessate</span><span class="sxs-lookup"><span data-stu-id="449b9-115">Affected APIs</span></span>|<ul><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32,System.Threading.CancellationToken)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.TimeSpan)?displayProperty=nameWithType></li></ul>|
