---
ms.openlocfilehash: 470fc2ddcfbb29a677cadb6e7e1d2e55784d7ac2
ms.sourcegitcommit: 5b6d778ebb269ee6684fb57ad69a8c28b06235b9
ms.translationtype: HT
ms.contentlocale: it-IT
ms.lasthandoff: 04/08/2019
ms.locfileid: "59236228"
---
### <a name="workflow-now-throws-original-exception-instead-of-nullreferenceexception-in-some-cases"></a><span data-ttu-id="b3c16-101">Il flusso di lavoro ora genera l'eccezione originale anziché NullReferenceException in alcuni casi</span><span class="sxs-lookup"><span data-stu-id="b3c16-101">Workflow now throws original exception instead of NullReferenceException in some cases</span></span>

|   |   |
|---|---|
|<span data-ttu-id="b3c16-102">Dettagli</span><span class="sxs-lookup"><span data-stu-id="b3c16-102">Details</span></span>|<span data-ttu-id="b3c16-103">In .NET Framework 4.6.2 e versioni precedenti, quando il metodo Execute di un'attività flusso di lavoro genera un'eccezione con un valore <code>null</code> per la proprietà <xref:System.Exception.Message>, il runtime del flusso di lavoro System.Activities genera un <xref:System.NullReferenceException?displayProperty=name>, occultando l'eccezione originale. In .NET Framework 4.7 viene generata l'eccezione occultata in precedenza.</span><span class="sxs-lookup"><span data-stu-id="b3c16-103">In the .NET Framework 4.6.2 and earlier versions, when the Execute method of a workflow activity throws an exception with a <code>null</code> value for the <xref:System.Exception.Message> property, the System.Activities Workflow runtime throws a <xref:System.NullReferenceException?displayProperty=name>, masking the original exception.In the .NET Framework 4.7, the previously masked exception is thrown.</span></span>|
|<span data-ttu-id="b3c16-104">Suggerimento</span><span class="sxs-lookup"><span data-stu-id="b3c16-104">Suggestion</span></span>|<span data-ttu-id="b3c16-105">Se il codice si basa sulla gestione di <xref:System.NullReferenceException?displayProperty=name>, modificarlo per intercettare le eccezioni che potrebbero essere generate da attività personalizzate.</span><span class="sxs-lookup"><span data-stu-id="b3c16-105">If your code relies on handling the <xref:System.NullReferenceException?displayProperty=name>, change it to catch the exceptions that could be thrown from your custom activities.</span></span>|
|<span data-ttu-id="b3c16-106">Ambito</span><span class="sxs-lookup"><span data-stu-id="b3c16-106">Scope</span></span>|<span data-ttu-id="b3c16-107">Secondario</span><span class="sxs-lookup"><span data-stu-id="b3c16-107">Minor</span></span>|
|<span data-ttu-id="b3c16-108">Versione</span><span class="sxs-lookup"><span data-stu-id="b3c16-108">Version</span></span>|<span data-ttu-id="b3c16-109">4.7</span><span class="sxs-lookup"><span data-stu-id="b3c16-109">4.7</span></span>|
|<span data-ttu-id="b3c16-110">Tipo</span><span class="sxs-lookup"><span data-stu-id="b3c16-110">Type</span></span>|<span data-ttu-id="b3c16-111">Runtime</span><span class="sxs-lookup"><span data-stu-id="b3c16-111">Runtime</span></span>|
|<span data-ttu-id="b3c16-112">API interessate</span><span class="sxs-lookup"><span data-stu-id="b3c16-112">Affected APIs</span></span>|<ul><li><xref:System.Activities.CodeActivity.Execute(System.Activities.CodeActivityContext)?displayProperty=nameWithType></li><li><xref:System.Activities.AsyncCodeActivity.BeginExecute(System.Activities.AsyncCodeActivityContext,System.AsyncCallback,System.Object)?displayProperty=nameWithType></li><li><xref:System.Activities.AsyncCodeActivity%601.BeginExecute(System.Activities.AsyncCodeActivityContext,System.AsyncCallback,System.Object)?displayProperty=nameWithType></li><li><xref:System.Activities.WorkflowInvoker.Invoke?displayProperty=nameWithType></li></ul>|
